name: first workflow

on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: self-hosted
    steps:
      - name: firstjob script
        shell: cmd
        run: echo Hello World! This is the first job
        
   secondjob:
       runs-on: self-hosted
       steps:
         - name: secondjob script
           shell: bash
           run: |
             echo this is second job
             echo and this is multiline script
